import streamlit as st
import pandas as pd
from pathlib import Path

st.set_page_config(layout="wide", page_title="NFL Playoff Hub | RouteTree Labs")

st.title("NFL Playoff Prediction Hub")
st.caption("Moneyline • Spreads (ATS) • Points | Notebook-generated results")

FILES = {
    "ml_fd":  Path("data/playoff_moneyline_fd.csv"),
    "ml_dk":  Path("data/playoff_moneyline_dk.csv"),
    "ats_fd": Path("data/playoff_ats_fd.csv"),
    "ats_dk": Path("data/playoff_ats_dk.csv"),
    "pts_fd": Path("data/playoff_points_fd.csv"),
    "pts_dk": Path("data/playoff_points_dk.csv"),
}

@st.cache_data
def load_csv(path: str) -> pd.DataFrame:
    return pd.read_csv(path)

def safe_load(path: Path, label: str) -> pd.DataFrame:
    if not path.exists():
        st.error(f"Missing file for **{label}**: `{path.as_posix()}`")
        st.info("Run your notebook to generate the playoff CSVs, then push them to GitHub.")
        st.stop()
    return load_csv(path.as_posix())

# Load
ml_fd  = safe_load(FILES["ml_fd"],  "Moneyline (FanDuel)")
ml_dk  = safe_load(FILES["ml_dk"],  "Moneyline (DraftKings)")
ats_fd = safe_load(FILES["ats_fd"], "ATS (FanDuel)")
ats_dk = safe_load(FILES["ats_dk"], "ATS (DraftKings)")
pts_fd = safe_load(FILES["pts_fd"], "Points (FanDuel)")
pts_dk = safe_load(FILES["pts_dk"], "Points (DraftKings)")

tab1, tab2, tab3 = st.tabs(["Moneyline", "Spreads (ATS)", "Points"])

with tab1:
    st.header("Moneyline Predictions")
    c1, c2 = st.columns(2)
    with c1:
        st.subheader("FanDuel")
        if "Home Win Probability" in ml_fd.columns:
            st.dataframe(ml_fd.style.format({"Home Win Probability": "{:.2%}"}), use_container_width=True)
        else:
            st.dataframe(ml_fd, use_container_width=True)

    with c2:
        st.subheader("DraftKings")
        if "Home Win Probability" in ml_dk.columns:
            st.dataframe(ml_dk.style.format({"Home Win Probability": "{:.2%}"}), use_container_width=True)
        else:
            st.dataframe(ml_dk, use_container_width=True)

with tab2:
    st.header("Against the Spread (ATS)")
    c1, c2 = st.columns(2)
    with c1:
        st.subheader("FanDuel")
        if "Home Cover Probability" in ats_fd.columns:
            st.dataframe(ats_fd.style.format({"Home Cover Probability": "{:.2%}"}), use_container_width=True)
        else:
            st.dataframe(ats_fd, use_container_width=True)

    with c2:
        st.subheader("DraftKings")
        if "Home Cover Probability" in ats_dk.columns:
            st.dataframe(ats_dk.style.format({"Home Cover Probability": "{:.2%}"}), use_container_width=True)
        else:
            st.dataframe(ats_dk, use_container_width=True)

with tab3:
    st.header("Points & Totals")
    c1, c2 = st.columns(2)
    with c1:
        st.subheader("FanDuel")
        st.dataframe(pts_fd, use_container_width=True)

    with c2:
        st.subheader("DraftKings")
        st.dataframe(pts_dk, use_container_width=True)

st.divider()
st.caption("Predictions generated by RouteTree Labs models. For informational/entertainment purposes only.")
